<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fan.summer</groupId>
    <artifactId>SwissKiJ-Plugin</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>SwissKiJ Official Plugins</name>
    <description>Official plugin collection for SwissKitJ.</description>

    <modules>
        <module>SwissKitJ-Plugin-HappyLearning</module>
        <module>SwissKitJ-Plugin-Qcc</module>
        <module>SwissKit-Plugin-Mouse</module>
    </modules>

</project>
